# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]



    # ...
    admin.actulaite:
        class: backBundle\Admin\actualiteAdmin
        arguments: [~, backBundle\Entity\actualite, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Actualite }
    admin.user:
            class: backBundle\Admin\userAdmin
            arguments: [~, FrontBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: User }

    app_bundle.service.listener:
            class: FrontBundle\EventListener\LoadDataListener
            arguments: [ "@doctrine.orm.entity_manager" ]
            tags:
                - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }