<?php

namespace AppBundle\Repository;

/**
 * pncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pncRepository extends \Doctrine\ORM\EntityRepository
{
}
